version: '3.4'

services:
  demo-app:
    build:
      dockerfile: Dockerfile
      context: ./
    hostname: demo-app
    ports:
      - "8080:8080"

  demo-app2:
    build:
      dockerfile: Dockerfile
      context: ./
    hostname: demo-app2
    ports:
      - "8081:8080"


  promotheus:
    image: prom/prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - "3000:3000"

  redis:
    container_name: redis
    image: "redis:5.0.5"
    ports:
      - "6379:6379"